application: monerochain-166203
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:


- url: /dist/(.+)
  static_files: dist/\1
  upload: dist/(.*)

- url: /.*
  mime_type: text/html
  static_files: dist/index.html
  upload:  dist/index.html


skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?tests$
- ^(.*/)?test$
- ^(.*/)?venv
- ^test/(.*/)?
- ^COPYING.LESSER
- ^README\..*
- \.gitignore
- ^\.git/.*
- \.*\.lint$
- ^fabfile\.py
- ^testrunner\.py
- ^grunt\.js
- ^node_modules/(.*/)?
